// Generated by delombok at Thu Nov 21 19:52:46 CST 2019
package com.moppy.core.device;

/**
 * Class to provide meta information for a device on the network.
 */
public class DeviceDescriptor {
    private String networkAddress;
    private byte deviceAddress;
    private byte minSubAddress;
    private byte maxSubAddress;

    public String getNetworkAddress() {
        return networkAddress;
    }

    public void setNetworkAddress(String networkAddress) {
        this.networkAddress = networkAddress;
    }

    public byte getDeviceAddress() {
        return deviceAddress;
    }

    public void setDeviceAddress(byte deviceAddress) {
        this.deviceAddress = deviceAddress;
    }

    public byte getMinSubAddress() {
        return minSubAddress;
    }

    public void setMinSubAddress(byte minSubAddress) {
        this.minSubAddress = minSubAddress;
    }

    public byte getMaxSubAddress() {
        return maxSubAddress;
    }

    public void setMaxSubAddress(byte maxSubAddress) {
        this.maxSubAddress = maxSubAddress;
    }

    @java.lang.SuppressWarnings("all")
    DeviceDescriptor(final String networkAddress, final byte deviceAddress, final byte minSubAddress, final byte maxSubAddress) {
        this.networkAddress = networkAddress;
        this.deviceAddress = deviceAddress;
        this.minSubAddress = minSubAddress;
        this.maxSubAddress = maxSubAddress;
    }


    @java.lang.SuppressWarnings("all")
    public static class DeviceDescriptorBuilder {
        @java.lang.SuppressWarnings("all")
        private String networkAddress;
        @java.lang.SuppressWarnings("all")
        private byte deviceAddress;
        @java.lang.SuppressWarnings("all")
        private byte minSubAddress;
        @java.lang.SuppressWarnings("all")
        private byte maxSubAddress;

        @java.lang.SuppressWarnings("all")
        DeviceDescriptorBuilder() {
        }

        @java.lang.SuppressWarnings("all")
        public DeviceDescriptorBuilder networkAddress(final String networkAddress) {
            this.networkAddress = networkAddress;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public DeviceDescriptorBuilder deviceAddress(final byte deviceAddress) {
            this.deviceAddress = deviceAddress;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public DeviceDescriptorBuilder minSubAddress(final byte minSubAddress) {
            this.minSubAddress = minSubAddress;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public DeviceDescriptorBuilder maxSubAddress(final byte maxSubAddress) {
            this.maxSubAddress = maxSubAddress;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public DeviceDescriptor build() {
            return new DeviceDescriptor(networkAddress, deviceAddress, minSubAddress, maxSubAddress);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "DeviceDescriptor.DeviceDescriptorBuilder(networkAddress=" + this.networkAddress + ", deviceAddress=" + this.deviceAddress + ", minSubAddress=" + this.minSubAddress + ", maxSubAddress=" + this.maxSubAddress + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static DeviceDescriptorBuilder builder() {
        return new DeviceDescriptorBuilder();
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DeviceDescriptor)) return false;
        final DeviceDescriptor other = (DeviceDescriptor) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$networkAddress = this.getNetworkAddress();
        final java.lang.Object other$networkAddress = other.getNetworkAddress();
        if (this$networkAddress == null ? other$networkAddress != null : !this$networkAddress.equals(other$networkAddress)) return false;
        if (this.getDeviceAddress() != other.getDeviceAddress()) return false;
        if (this.getMinSubAddress() != other.getMinSubAddress()) return false;
        if (this.getMaxSubAddress() != other.getMaxSubAddress()) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DeviceDescriptor;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $networkAddress = this.getNetworkAddress();
        result = result * PRIME + ($networkAddress == null ? 43 : $networkAddress.hashCode());
        result = result * PRIME + this.getDeviceAddress();
        result = result * PRIME + this.getMinSubAddress();
        result = result * PRIME + this.getMaxSubAddress();
        return result;
    }
}
