// Generated by delombok at Thu Nov 21 19:52:46 CST 2019
package com.moppyandroid.com.moppy.core.midi;

import com.moppyandroid.com.moppy.core.status.StatusBus;
import com.moppyandroid.com.moppy.core.status.StatusUpdate;

import java.io.Closeable;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Logger;

import jp.kshoji.javax.sound.midi.InvalidMidiDataException;
import jp.kshoji.javax.sound.midi.MetaEventListener;
import jp.kshoji.javax.sound.midi.MetaMessage;
import jp.kshoji.javax.sound.midi.MidiSystem;
import jp.kshoji.javax.sound.midi.MidiUnavailableException;
import jp.kshoji.javax.sound.midi.Sequence;
import jp.kshoji.javax.sound.midi.Sequencer;
import jp.kshoji.javax.sound.midi.Transmitter;

/**
 * Wrapper around the Java MIDI sequencer for playing MIDI files.
 * <p>
 * Additionally provides feedback to listeners about the current state of the sequencer.
 */
public class MoppyMIDISequencer implements MetaEventListener, Closeable {
    private static final Logger LOG = Logger.getLogger(MoppyMIDISequencer.class.getName());
    private final Sequencer seq;
    private final StatusBus statusBus;
    private boolean autoReset = false;

    public MoppyMIDISequencer(StatusBus statusBus, MoppyMIDIReceiverSender receiverSender) throws MidiUnavailableException {
        this.statusBus = statusBus;
        this.statusBus.registerConsumer(receiverSender); // Register receiverSender to send seq messages to network
        seq = MidiSystem.getSequencer(false);
        seq.open();
        // TODO: Probably needs to be fixed in order for proper operation
        // Since there is no Gervill on Android, we are having trouble getting a default transmitter to register MIDI events with
        //Transmitter x = seq.getTransmitter();
        //x.setReceiver(receiverSender);
        seq.addMetaEventListener(this);
    }

    @Override
    public void close() throws IOException {
        seq.close();
    }

    @Override
    public void meta(MetaMessage meta) {
        // Handle tempo changes
        if (meta.getType() == 81) {
            int uSecondsPerQN = 0;
            uSecondsPerQN |= meta.getData()[0] & 255;
            uSecondsPerQN <<= 8;
            uSecondsPerQN |= meta.getData()[1] & 255;
            uSecondsPerQN <<= 8;
            uSecondsPerQN |= meta.getData()[2] & 255;
            int newTempo = 60000000 / uSecondsPerQN;
            setTempo(newTempo);
        }
        else
            // Handle end-of-track events
            if (meta.getType() == 47) {
                seq.setTickPosition(0); // Reset sequencer so we can press "play" again right away
                //MrSolidSnake745: Exposing end of sequence event to status consumers
                statusBus.receiveUpdate(StatusUpdate.sequenceEnd(autoReset));
            }
    }

    public void play() {
        seq.start();
        statusBus.receiveUpdate(StatusUpdate.SEQUENCE_START);
    }

    public void pause() {
        seq.stop();
        statusBus.receiveUpdate(StatusUpdate.SEQUENCE_PAUSE);
    }

    public void stop() {
        seq.stop();
        seq.setTickPosition(0);
        statusBus.receiveUpdate(StatusUpdate.sequenceEnd(true)); // Always reset when stop button is pressed
    }

    public boolean isPlaying() {
        return seq.isRunning();
    }

    // TODO: mark changed
    public void loadSequence(Sequence sequenceToLoad) throws InvalidMidiDataException {
        seq.setSequence(sequenceToLoad);
        statusBus.receiveUpdate(StatusUpdate.sequenceLoaded(sequenceToLoad));
        LOG.info(String.format("Loaded sequence with %s tracks", sequenceToLoad.getTracks().length - 1)); // -1 for system track?
    }

    public long getSecondsLength() {
        return TimeUnit.SECONDS.convert(seq.getMicrosecondLength(), TimeUnit.MICROSECONDS);
    }

    public long getSecondsPosition() {
        return TimeUnit.SECONDS.convert(seq.getMicrosecondPosition(), TimeUnit.MICROSECONDS);
    }

    public void setSecondsPosition(long seconds) {
        seq.setMicrosecondPosition(TimeUnit.SECONDS.toMicros(seconds));
    }

    public void setTempo(float newTempo) {
        seq.setTempoInBPM(newTempo);
        statusBus.receiveUpdate(StatusUpdate.tempoChange(newTempo));
        LOG.info(String.format("Tempo changed to %s", newTempo));
    }

    @java.lang.SuppressWarnings("all")
    public void setAutoReset(final boolean autoReset) {
        this.autoReset = autoReset;
    }
}
